"""attempts & has_won

Revision ID: 848843af0c0f
Revises: 73ffa12c03c8
Create Date: 2023-03-30 13:36:21.370306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848843af0c0f'
down_revision = '73ffa12c03c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('has_won', sa.Boolean(), server_default='False', nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'has_won')
    op.drop_column('users', 'attempts')
    # ### end Alembic commands ###
